"""add user_uid foreignkey to url

Revision ID: 3a6479d4d184
Revises: d0bd178840db
Create Date: 2026-05-18 04:03:18.130003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a6479d4d184'
down_revision: Union[str, Sequence[str], None] = 'd0bd178840db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_urls_user_id'), 'urls', ['user_id'], unique=False)
    op.create_foreign_key('fk_urls_user_id_users', 'urls', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_urls_user_id_users', 'urls', type_='foreignkey')
    op.drop_index(op.f('ix_urls_user_id'), table_name='urls')
    op.drop_column('urls', 'user_id')
    # ### end Alembic commands ###
